// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXF0Zpxfn8a9lALRLBJcXgjHvlCPBrlIM',
    appId: '1:917115441726:web:6ca2560f2e5a84ff00b76f',
    messagingSenderId: '917115441726',
    projectId: 'fruit-shop-app-33e24',
    authDomain: 'fruit-shop-app-33e24.firebaseapp.com',
    storageBucket: 'fruit-shop-app-33e24.firebasestorage.app',
    measurementId: 'G-H6D5SPSY8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvNjz37DTK0-Xihp_W6K0WiU6dqeOGNMk',
    appId: '1:917115441726:android:557da8b34be15cf500b76f',
    messagingSenderId: '917115441726',
    projectId: 'fruit-shop-app-33e24',
    storageBucket: 'fruit-shop-app-33e24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwPdyfDOz9XPIhEqbbkwuBcULe5c507DQ',
    appId: '1:917115441726:ios:f88ab0882455cee900b76f',
    messagingSenderId: '917115441726',
    projectId: 'fruit-shop-app-33e24',
    storageBucket: 'fruit-shop-app-33e24.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwPdyfDOz9XPIhEqbbkwuBcULe5c507DQ',
    appId: '1:917115441726:ios:f88ab0882455cee900b76f',
    messagingSenderId: '917115441726',
    projectId: 'fruit-shop-app-33e24',
    storageBucket: 'fruit-shop-app-33e24.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXF0Zpxfn8a9lALRLBJcXgjHvlCPBrlIM',
    appId: '1:917115441726:web:259351b785e54b3800b76f',
    messagingSenderId: '917115441726',
    projectId: 'fruit-shop-app-33e24',
    authDomain: 'fruit-shop-app-33e24.firebaseapp.com',
    storageBucket: 'fruit-shop-app-33e24.firebasestorage.app',
    measurementId: 'G-Q1FDKHLCXD',
  );
}
